fix path to java fix:https://github.com/Zimbra-Community/mailing-lists/issues/1

diff --git a/bin/process_mailinglists b/bin/process_mailinglists
--- a/bin/process_mailinglists
+++ b/bin/process_mailinglists
@@ -1,4 +1,21 @@
 #!/bin/bash
+
+# We only support java versions bundled with Zimbra
+if [[ -x "/opt/zimbra/common/bin/java" ]]
+then
+   #8.7
+    [[ ":$PATH:" != *":/opt/zimbra/common/bin:"* ]] && PATH="/opt/zimbra/common/bin:${PATH}"
+    export PATH
+elif  [[ -x "/opt/zimbra/java/bin/java" ]]
+then
+    #8.6
+    [[ ":$PATH:" != *":/opt/zimbra/java/bin:"* ]] && PATH="/opt/zimbra/java/bin:${PATH}"
+    export PATH
+else
+    echo "Java is not found in /opt/zimbra"
+    exit 1
+fi
+
 /usr/local/sbin/add_distributionlists
 java -jar /usr/local/sbin/processor.jar
 date >> /var/log/mailinglists.log
